[package]
name = "cssparser-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.15.0"
rand = "0.8.5"
indexmap = "2.7.0"
smallvec = "1.7.0"
criterion = { version = "0.5", features = ["html_reports"] }

[profile.release]
debug = "full"

[[bench]]
name = "benchmark"
harness = false